name: Namex Pay CI

on:
  pull_request:
    paths:
      - "services/namex-pay/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: "services/namex-pay"

jobs:
  namex-pay-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "namex-pay"
      working_directory: "services/namex-pay"
      codecov_flag: "namexpay"
      skip_isort: "true"
      skip_black: "true"